### ISSUE TITLE
Can the files from gba-linker-script package just be included in the Docker image?

### ISSUE THREAD

**Issue by TricksterGuy** [gt-cs2110/cs2110docker#1]
It'd save me some trouble, I'd rather not create another thing on launchpad for it

To not break the GBA Makefiles. The files are placed in /opt/cs2110-tools/

**Comment by TricksterGuy** [comment]
Alternatively you can just download the deb from [launchpad](https://launchpad.net/~tricksterguy87/+archive/ubuntu/ppa-gt-cs2110/+files/cs2110-gba-linker-script_1.1.2-0ubuntu1~ppa1~bionic1_amd64.deb) and install it manually via dpkg. The actual deb package isn't actually tied to a specific version of ubuntu and should be able to be installed without any issues.

**Comment by kanwren** [comment]
I'll implement whichever you think is a better idea. I'd prefer to just add the files directly to the image, but if you think fetching the deb is better, that's fine too.

**Comment by TricksterGuy** [comment]
The easiest would probably be to commit the deb file and install it in the complxGBA.sh script using dpkg.
