### ISSUE TITLE
Add text editor (vi)

### ISSUE THREAD

**Issue by thayes46** [gt-cs2110/cs2110docker#11]
Dr. Conte has requested on a few occasions a text editor in docker for classroom examples, vi would be fine and is the recommendation.

**Comment by kanwren** [comment]
Are things like syntax highlighting needed? For reference, `vim` is 70 MB, while `vim-tiny` is basically `vi` and is only 0.5MB.

**Comment by kanwren** [comment]
70 MB isn't really that much, but I'm becoming ever more wary of unnecessarily driving up image size

**Comment by sameer-s** [comment]
I would say that if it's just for classroom examples / small changes, then `vim-tiny` is fine. I'd also add that `nano` is even smaller and would be more usable by the average student.

**Comment by kanwren** [comment]
`vim-tiny` and `nano` it is, then
