### ISSUE TITLE
Build an ARM image

### ISSUE THREAD

**Issue by sameer-s** [gt-cs2110/cs2110docker#12]
See title

With a lot of students using M1 Macs now, it's become more and more necessary to have an ARM image. Running those systems on an x86 image causes a lot of lag which makes CircuitSim and Complx basically unusable.

The main change here will require an ARM build of Complx, it also makes sense while doing this to move towards building Complx from source

**Comment by kanwren** [comment]
For future reference, some notes about multiarch builds:

- Can run `docker run --rm --privileged multiarch/qemu-user-static --reset -p yes` to allow running multiarch images through qemu, assuming qemu is already registered with binfmt
- Can build multiarch images through buildx, e.g. `docker buildx build --platform linux/amd64,linux/arm64 .`

**Comment by kanwren** [comment]
Got some funky inconsistent builds getting the scripts to run properly, but everything seems to go well up until installing `libc6-i386` in `src/install/tools/cTools.sh`, which makes perfect sense.

**Comment by TricksterGuy** [comment]
> The main change here will require an ARM build of Complx, it also makes sense while doing this to move towards building Complx from source

I don't see why suggesting to build complx from source? Launchpad can be configured from my end to produce the arm binaries. I should add someone from here as a contributor if necessary.

---

If you need someone with an M1 Mac for testing I purchased one earlier this year. Just saying!

**Comment by TricksterGuy** [comment]
Found the settings. Note if we're moving forward with this I will need some more information

![Screenshot from 2021-11-09 19-54-41](https://user-images.githubusercontent.com/824564/141046997-179c918d-42c4-4006-a70c-91169088e38b.png)

which one?

 ARM ARMv8 (arm64)
 ARM ARMv7 Hard Float (armhf)

**Comment by kanwren** [comment]
arm64 is the correct one, ARMv8

**Comment by sameer-s** [comment]
I just wanted to follow up on this and ask if there's anything I can do to help (I have an M1 Mac Mini if any testing is needed). Ideally (if possible) I'd like to have an image ready to go by the start of the semester.

**Comment by TricksterGuy** [comment]
I just enabled armv8 builds of complx I will report back in a few hours to see if that actually built a binary package for me. Otherwise I will need to fix whatever build errors are present.

**Comment by sameer-s** [comment]
Appears like it was successful (on Launchpad), I'll work tonight/tomorrow on building an ARM image based on Nicole's info above

**Comment by TricksterGuy** [comment]
Mmm still need to do nin10kit yeah.

**Comment by sameer-s** [comment]
Tried putting together a build tonight (changed `libc6-i386` to `libc6` and removed the bits about nin10kit to see if there are any other issues).

Ran into issues with the GBA linker script since that's an arm64 deb. I looked into it and it seems that the mGBA debs on GitHub (up to latest version, 0.9.3) are also arm64 only, although there are multiple architectures on launchpad (only up to 0.9.2). I'll investigate / try to find a solution a bit more tomorrow.

**Comment by TricksterGuy** [comment]
GBA linker script while an arm64.deb shouldn't contain any compiled code I should have marked it architecture independent.

Well I can put mgba up in my ppa and produce a armv8 build. That's an option, but not optimal. I'm sure they have build tools to go from source code to packages or just perhaps they have an launchpad config too. May just ask them to enable it like I have?

**Comment by sameer-s** [comment]
Yep, looks like `--force-architecture` does the trick for the linker script.

I think we can just pull MGBA from Launchpad, being one minor version out of date is no big deal.

I'm currently working on getting a build of TigerVNC (there are no ARM binaries of version 1.8.0 and the newer versions aren't backwards-compatible so don't work with our scripts), I think we should be good to go for the start of the semester after that.

**Comment by sameer-s** [comment]
I have this basically fully working now, need to clean some stuff up but will submit a PR soon

Brandon, can you enable ARM builds of nin10kit when you get a chance?
