### ISSUE TITLE
Add some text about wsl --shutdown

### ISSUE THREAD

**Issue by sameer-s** [gt-cs2110/cs2110docker#14]
With the new Windows setup, we always have at least one student every semester that makes a Piazza/Ed post telling other students how to shut down the WSL VM. It doesn't make sense for `./cs2110docker.sh` to do that automatically, since some students may be using WSL 2 for other purposes, but we should at least add some text letting students know that this is an option and that it may passively eat up some memory if the VM is left running.

**Comment by kanwren** [comment]
Should we mention anything about restricting WSL resource usage anywhere, e.g. through a `~/.wslconfig`?

**Comment by kanwren** [comment]
Also, the best detection is probably if the `wsl` command exists, and `docker-desktop` shows up in the output of `wsl --list -q`

**Comment by sameer-s** [comment]
I'm not sure how valuable including info on restricting resource usage really would be since having students restrict their container's resources -> slower container -> more complaints. We could give them the option but I don't know if the value gained will really be worth the extra complication.

It seems that we can use `wsl --terminate` to shut down a specific running distro so I'd say we can use the detection you suggested and just shut it down if it's present when `./cs2110docker.sh stop` is run. I don't really know if we'll run into an issue where too many students are using Docker Desktop for other purposes, and Docker should pretty much just start it up again for them if needed.
