### ISSUE TITLE
cs2110docker.sh -it fails on some Windows systems

### ISSUE THREAD

**Issue by sameer-s** [gt-cs2110/cs2110docker#18]
`the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'`

An easy workaround is adding winpty to that command in cs2110docker.sh, but that's nontrivial to students / they don't know to do it.

I believe the default option when installing Git Bash now is to use mintty so we will be seeing this more and more.

**Comment by kanwren** [comment]
Does `winpty` work here? I've had issues in the past. Also, it wouldn't be too hard to add a check in the script for this, but I'd like to be sure there's no better way first.

**Comment by sameer-s** [comment]
`winpty` seems to work as far as I can tell, so adding a check was pretty much my plan.

**Comment by kanwren** [comment]
Do you want me to take this, then? Should we just add a check for if `winpty` exists and attempt to run through that?

**Comment by sameer-s** [comment]
I totally missed this, but I think that would work.

I think there's some cases where `winpty` exists, but isn't needed, but since I really haven't had any issues with it (and this is after most of a semester of recommending students use it) I'm gonna assume that's probably not a problem.
