### ISSUE TITLE
Any plans on bumping up to Ubuntu 22.04?

### ISSUE THREAD

**Issue by TricksterGuy** [gt-cs2110/cs2110docker#26]
It'd be **real** nice for me since the versions of CMake across LTS versions are diverging in behavior and making these packages take longer than it should with me having to chase down Cmake issues.

![Screenshot from 2022-09-03 22-44-33](https://user-images.githubusercontent.com/824564/188299388-cee9bf34-fe8d-4973-82f1-b971214782cf.png)

**Comment by sameer-s** [comment]
Sure, there are some conveniences for us in there as well. Hopefully it should just work but I'll mess around with it this semester and plan to have it deployed for the spring

**Comment by TricksterGuy** [comment]
Yeah, not urgent anymore. The issue was found last night, but it is dang annoying to spend one day debugging.

I'd appreciate keeping this up to date with the most recent LTS Ubuntu release. 

A newer C++ compiler and CMake are nice to have! Especially since newer code is using the C++17/20 standards which require nearly the latest.
