### ISSUE TITLE
Large image size

### ISSUE THREAD

**Issue by kanwren** [gt-cs2110/cs2110docker#7]
The image is currently 4.17GB, and it would help the students out a lot if we shrank it. Some initial things to consider:

- `/usr/lib/arm-none-eabi/newlib/thumb` takes up an enormous amount of space and might not be needed for what we're doing with GBA
- Cleanup steps for artifacts should run in the same Docker layer that produced them, or they will contribute to the total image size.
- `--no-install-recommends` could be applied liberally to shave off some unnecessary packages

**Comment by sameer-s** [comment]
Marking as resolved, see
https://github.com/gt-cs2110/cs2110docker/commit/96694a83e4fed041b062d61f0132f3284f583f22
https://github.com/gt-cs2110/cs2110docker/commit/91e5d90e08f8661a6eeac755626697198f8ff5a8
